name: Build

on: 
  push:
    branches:
      - master
      - feature/*
      - release/*
  pull_request:
    branches:
      - master
      - feature/*
      - release/*
  workflow_dispatch:

permissions:
  contents: write
  checks: write
  pull-requests: read

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: hello world
        shell: pwsh
        run: |
          echo "hello world!"

  deploy-preview:
    needs: build
    runs-on: ubuntu-latest
    # <<< Das ist der QA-Gate-Schalter
    environment:
      name: qa-approval     # hat Required reviewers + Prevent self-review
      url: ${{ steps.deploy.outputs.url }}
    steps:
      - name: waiting for approval
        shell: pwsh
        run: |
          echo "waiting for approval!"